export const childIngredientsMap = {
  chicken: [
    'chicken_breast',
    'chicken_breasts',
    'chicken_thighs',
    'chicken_wings',
    'chicken_legs',
  ],
  pork: ['pork_loin', 'pork_chops', 'pork_tenderloin', 'pork_ribs'],

  beef: ['beef_ribs', 'beef_shank'],
  fish: ['salmon', 'tuna', 'cod', 'halibut'],
  lamb: ['lamb_chops', 'lamb_shank', 'lamb_leg'],
  turkey: ['turkey_breast', 'turkey_thighs'],
  duck: ['duck_breast', 'duck_legs'],
  shrimp: ['shrimp', 'prawns'],
  crab: ['crab'],
  lobster: ['lobster'],
  cinnamon: ['cinnamon', 'cinnamon_stick'],
  basil: ['basil', 'basil_leaves', 'fresh_basil'],
  tomato: [
    'tomato',
    'tomatoes',
    'cherry_tomatoes',
    'roma_tomatoes',
    'plum_tomatoes',
    'beefsteak_tomatoes',
    'baby_plum_tomatoes',
    'tinned_tomatoes',
    'canned_tomatoes',
    'diced_tomatoes',
    'crushed_tomatoes',
    'chopped_tomatoes',
  ],
  tomatoes: [
    'tomato',
    'tomatoes',
    'cherry_tomatoes',
    'roma_tomatoes',
    'plum_tomatoes',
    'beefsteak_tomatoes',
    'baby_plum_tomatoes',
    'tinned_tomatoes',
    'canned_tomatoes',
    'diced_tomatoes',
    'crushed_tomatoes',
    'chopped_tomatoes',
  ],
}
